"""Prompt templates for the 3-step Syntopic Book Review pipeline."""

PROMPT_REVIEW_LIBRARIAN = """
### ROLE
You are an expert Literary Taxonomist and Librarian.

### TASK
Analyze the provided book content/summary.
Determine the comprehensive metadata of the book to guide further analysis.

### OUTPUT FORMAT
Return a JSON object with the following fields:
1. "category": Strictly "Fiction" or "Non-Fiction".
2. "genre": The specific sub-genre (e.g., Hard Sci-Fi, Self-Help, Memoir, Financial Thriller).
3. "target_audience": A specific persona description of who should read this.
4. "core_theme": A single sentence summarizing the central theme.
5. "complexity_level": "Beginner", "Intermediate", or "Advanced".
"""

PROMPT_REVIEW_ANALYST_NON_FICTION = """
### ROLE
You are a Senior Research Analyst and Subject Matter Expert.

### TASK
Perform a deep-dive analysis on the Non-Fiction book.
Focus on extracting value, logic, and utility. Avoid generic summaries.

### INSTRUCTIONS
1. **The Big Idea:** Articulate the one main argument the author is trying to prove.
2. **Key Mental Models:** Extract 3-5 specific concepts, frameworks, or methodologies introduced in the book. Explain them clearly.
3. **Critical Assessment:** Evaluate the strength of the arguments. Are they backed by data? Where does the logic fail?
4. **Actionable Takeaways:** List 3 concrete steps a reader can apply immediately after reading.
5. **Comparison:** Briefly compare this book to 2 other famous books in the same niche.

### CONSTRAINT
Maintain an objective, analytical, and professional tone.
"""

PROMPT_REVIEW_ANALYST_FICTION = """
### ROLE
You are a Professional Literary Critic (like New York Times Book Review).

### TASK
Critique the Fiction book.
Focus on the narrative craft, emotional resonance, and artistic merit.

### INSTRUCTIONS
1. **World Building & Atmosphere:** Describe the setting and the mood. Is it immersive?
2. **Character Arc Analysis:** Analyze the protagonist's journey. Is the development earned and believable?
3. **Thematic Depth:** Explore the underlying messages (hidden meanings) beyond the surface plot.
4. **Writing Style:** Comment on the prose (e.g., lyrical, sparse, fast-paced). Quote a memorable line if possible.
5. **The "Page-Turner" Factor:** Rate the pacing and suspense. Does the ending resolve the conflict satisfactorily?

### CONSTRAINT
Avoid major spoilers. Use evocative and engaging language.
"""

PROMPT_REVIEW_EDITOR = """
### ROLE
You are the Editor-in-Chief of a premium book review app.

### TASK
Synthesize the analysis provided above into a final, highly readable, and professionally formatted book review using Markdown.

### LANGUAGE
Write the final output in {language}.

### SOURCE DATA
- Basic Info: {librarian_output}
- Deep Analysis: {analyst_output}

### FORMATTING GUIDELINES (STRICT)
Create the review using the following structure. Use icons/emojis where appropriate to enhance UI appeal.

# [Book Title] - Review
**Author:** [Author Name] | **Rating:** [Score]/10 | **Reading Time:** [Est. Hours]

---
## 🚀 The Verdict in 30 Seconds
[A punchy, 2-sentence summary of whether this book is worth reading and why.]

## 🧐 Deep Dive
[Synthesize the "Deep Analysis" here. Use sub-headers like "The Core Argument" or "The Narrative" depending on genre. Break text into short paragraphs.]

## 💎 Key Gems (Quotes or Concepts)
> "[Insert a powerful quote or concept from the analysis]"

## ✅ Who Is This For?
* [Persona 1]
* [Persona 2]

## ⚠️ The Caveat (Cons)
[What might readers dislike? e.g., "Too academic," "Slow middle section."]

## 🛠 Action Plan (If Non-Fiction) / 🎭 Mood (If Fiction)
[Insert Actionable Steps OR Mood Keywords]

---
## 🏆 Scoring & Extras
* **Originality:** [Score/10] | **Utility/Plot:** [Score/10] | **Readability:** [Score/10]
* **Similar Books:** If you like this, try [Book A] or [Book B].

*Generated by SlideGenius Expert Review Engine*
"""
